use std::error::Error;

pub async fn insert_new_row() -> Result<(), Box<dyn Error>> {
    Ok(())
}
